accuracy:
  _target_: sklearn.metrics.accuracy_score
f1:
  _target_: sklearn.metrics.f1_score
roc_auc:
  _target_: sklearn.metrics.roc_auc_score
mathews:
  _target_: sklearn.metrics.matthews_corrcoef
