data:
  path: ${oc.env:ROOT_DIR}/data/chem_subsets/new_latent/carbons/carbons_bloom2013_clf_3_pubchem.feather
  savename: Carbons_Bloom2013
  savedir: ${oc.env:ROOT_DIR}/runs/chem_subsets/Final/dummies/${data.savename}_${seed}

n_trials: 100

seed: 42

kfold_params:
  n_splits: 5
  seed: ${seed}
  shuffle: true

metric:
  _target_: sklearn.metrics.roc_auc_score

testing:
  test_dataset: null
  test_frac: 0.2 # fraction of data to use for testing,
  #Not considered if a separate test dataset is provided

run_type: full # one of full, geno_only, chem_only,

dummy: # for creating baseline models
  run: false # When false we don't care
  strategy: stratified # strategy compatible with sklearn.dummy.DummyClassifier

model_params:
  boosting: gbdt # gbdt, dart, rf

models:
  LogReg:
    name: LogReg
    model_savename: ${data.savedir}_${seed}/${models.LogReg.name}.pkl # A folder is created for each seed, useful when running multiple seeds

  SVM:
    name: SVM
    model_savename: ${data.savedir}_${seed}/${models.SVM.name}.pkl

  RandomForest:
    name: RandomForest
    model_savename: ${data.savedir}_${seed}/${models.RandomForest.name}.pkl

  Boosting:
    name: Boosting
    # device: "cuda:1"
    model_savename: ${data.savedir}_${seed}/${models.Boosting.name}.pkl
