model_types:
  - Boosting
  - RandomForest

run_type: full # Must be one of full, geno_only, chem_only, dummy

run_path: /home/rajeeva/Project/runs/chem_subsets/Final/
out_path: /home/rajeeva/Project/boosting/performance/Final/
data_path: /home/rajeeva/Project/data/chem_subsets/new_latent/carbons/

data_paths:
  Bloom2013: ${data_path}/carbons_bloom2013_clf_3_pubchem.feather
  Bloom2015: ${data_path}/carbons_bloom2015_clf_3_pubchem.feather
  Bloom2019: ${data_path}/carbons_bloom2019_clf_3_pubchem.feather
  Bloom2019_BYxM22: ${data_path}/carbons_bloom2019_BYxM22_clf_3_pubchem.feather
  Bloom2019_RMxYPS163: ${data_path}/carbons_bloom2019_RMxYPS163_clf_3_pubchem.feather
